# Generated by Django 5.0.2 on 2024-02-23 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='post',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='uuid',
        ),
    ]
