# Generated by Django 5.0.2 on 2024-02-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_comment_uuid_remove_post_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author_name',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='author_name',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
