# Generated by Django 5.0.2 on 2024-02-23 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_comment_author_name_post_author_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='usr',
        ),
    ]
