# Generated by Django 5.0.2 on 2024-02-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_like_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='not_intr',
            field=models.BooleanField(default=True),
        ),
    ]
