# Generated by Django 5.0.2 on 2024-02-24 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_like_not_intr'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Like',
            new_name='Likenumber',
        ),
    ]
